### ISSUE TITLE
Setting Color with Flow not working correct

### ISSUE THREAD

**Issue by CyberSponk** [athombv/com.osram.lightify.zigbee#1]
Color-Setting with a Flow works not correct:
Changing Color of the Bulb with a Flow the choosen Color (RGB-Values or Color-Picker) not set on the Bulb, e.g. choosing Red in the settings of the Flow-Card the Bulb is White-Yellow. If i run the Flow two (sometimes three) times the choosen Color set on the Bulb.

Homey 1.5.0-Rc2 / Lightify v1.0.4 - 02.08.17 Beta / Lightify A60 RGBW with latest Firmware

**Comment by RobinBol** [comment]
This should be fixed by now, if you download the app from github you can test it already. If it is not fixed please re-open this issue.
