### ISSUE TITLE
Osram Lightify Gardenspot

### ISSUE THREAD

**Issue by CyberSponk** [athombv/com.osram.lightify.zigbee#11]
In contenuation of this https://github.com/athombv/com.osram.lightify.zigbee/issues/4 Thread here the Information of the Garden-Spot:

![gardenspot](https://user-images.githubusercontent.com/26149030/31128005-b7b6bd10-a850-11e7-9848-9df2674112fc.png)

Thanks to @RobinBol for including the GU10 :-) last Week.

**Comment by RobinBol** [comment]
Thanks for the info, but I still need to know what its capabilities are, I guess `onoff` and `dim`, but maybe also `light_temperature`?

**Comment by CyberSponk** [comment]
Yes, On/Off, Dim and Color > The same as the GU10RGBW.

**Comment by RobinBol** [comment]
Add the gardenspot to the beta version of the Osram zigbee app!

**Comment by CyberSponk** [comment]
Hero. Thanks.
