### ISSUE TITLE
Homey Offline after Deleting/Unpairing a Bulb

### ISSUE THREAD

**Issue by CyberSponk** [athombv/com.osram.lightify.zigbee#3]
Pairing works fine. Only when Deleting/Unpairing a Bulb Homey goes Offline for some Minutes.

Homey 1.5.0-Rc2 / Lightify v1.0.4 - 02.08.17 Beta / Lightify A60 RGBW with latest Firmware

**Comment by bvdbos** [comment]
related to https://github.com/athombv/homey/issues/1724 ?

**Comment by bvdbos** [comment]
As 1724 is fixed, this might be fixed too. Can't confirm this for ikea-devices btw.

**Comment by CyberSponk** [comment]
Yes. Works correct on 1.5.0-RC6 > Tested it with a Lightify GU10 and A60.
