### ISSUE TITLE
Missing GU10 RGB, White and Garden-Spot

### ISSUE THREAD

**Issue by CyberSponk** [athombv/com.osram.lightify.zigbee#4]
Missing Osram Lightify GU10 RGBW, GU10 White and Garden-Spot in the App.

**Comment by dvanp** [comment]
And E14 tunable white as well.

**Comment by dvanp** [comment]
I've just tested the E14:
`"manufacturerName": "OSRAM",
        "productId": "Classic B40 TW - LIGHTIFY",
        "deviceId": 544,
        "profileId": 49246,`
So it differs only in productId from the E27/A60. 

I've added it in the productId array and on/off and dimming work, but **light_temperature doesn't work**. Tried adding it as a separate device: same result.

**Comment by RobinBol** [comment]
To which driver did you add the productId of the E14? Was the temperature slider available in the mobile card? (did you use the latest version of the osram app?)

**Comment by dvanp** [comment]
I added it to the "lightify_white" driver. Temperature slider is available in the mobile card and I forked just after your "Fix device class Plug" commit.

**Comment by RobinBol** [comment]
Strange that light temperature doesn't work, this app uses a generic driver that should work for all zigbee lights, if you run the app with `athom project --run` do you see any relevant logging that might indicate a bug? If not I can not really help, will need the device to test some things.

**Comment by dvanp** [comment]
Ah, there we go:
`2017-08-21 19:23:59 [log] [ManagerDrivers] [lightify_white] [1] registerMultipleCapabilityListener() { light_temperature: 0.44 } { light_temperature: {} }`

`2017-08-21 19:23:59 [err] [ManagerDrivers] [lightify_white] [1] capabilitySetObj light_temperature lightingColorCtrl is error Error: capability_set_is_not_a_function_or_string
    at LightifyWhiteZigBee._getCapabilityObj (/node_modules/homey-meshdriver/lib/zigbee/ZigBeeDevice.js:297:10)
    at registerMultipleCapabilityListener (/node_modules/homey-meshdriver/lib/zigbee/ZigBeeDevice.js:162:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by RobinBol** [comment]
Really strange, it almost seems like the device does not support lightingColorCtrl. You could try to debug this further, I don't know about your programming skills, but for me it is really hard to fix it it this way.

**Comment by CyberSponk** [comment]
Here the two GU10 (PAR16):
<img width="269" alt="par16rgbw" src="https://user-images.githubusercontent.com/26149030/29535708-30f7fb4c-86bb-11e7-89c1-61b8be6aef32.png">
<img width="220" alt="par16tw" src="https://user-images.githubusercontent.com/26149030/29535709-30fd90fc-86bb-11e7-89d6-f7cddd4f22ba.png">

@RobinBol "finding the productId and add them to the app.json. Then pair again and it should work." > Didn't know how this works :-(.

**Comment by dvanp** [comment]
My programming skills are awesome, but not in this particular field.

Could it be old firmware on the bulbs? If you could add it to the app anyway maybe we could find out if it works for others (like @bsnellen in #7).

**Comment by bsnellen** [comment]
Not all Lightify plug have id Plug 2, one of my plugs has id "Plug - LIGHTIFY".  this makes it register as generic zigbee device. After making a copy in app.json the plug is working fine.

**Comment by RobinBol** [comment]
@dvanp haha ok, well Homey is really easy to program for, check out our [docs](https://apps.developer.athom.com/)! I really don't like adding devices for which I do not know if it works, this will probably cause people quite some headache. I could add it on a different branch if people are capable of side loading an app from GitHub? If someone can then test it and verify it works I will add it to the app.

@bsnellen Thanks for the heads up, will add your `Plug - LIGHTIFY ` id to the app!

**Comment by CyberSponk** [comment]
@RobinBol Could you please add the "PAR16 50 TW", too > See Postings two Days ago > Screenshots from me. Thanks.

**Comment by RobinBol** [comment]
I would prefer to create a separate driver for that with separate icons, so that it is clear for others which devices we support. I'll add it when I find the time.

**Comment by CyberSponk** [comment]
Wrote because seen that the "PAR16 50 RGB" is included.

**Comment by RobinBol** [comment]
That should then also go in the separate driver, good catch.

**Comment by dvanp** [comment]
@RobinBol different branch is a good idea, I guess.
I'll look into if I can try to fix it myself, but don't have a lot of time on my hands to do so now, it might take months 😞

**Comment by CyberSponk** [comment]
Hmm. Since February Athom promised me with Lightify. Yupp.

**Comment by bsnellen** [comment]
I am having trouble using lightify E14 bulb in flows... when turning in the bulb in the devices section, every click turns the bulb on and off directly every time within one second.  when turning on or off  the same bulb in a flow is doesnt work 3 out of 5 times and when it does work it takes the bulb 2 to 5 seconds to actually turn off.. 

whats different from clicking on a bulb in devices and activating a flow ??

**Comment by Benjong** [comment]
Trying to add E14 bulbs also. First added as the E27 white bulb. Worked, but only on/off control.
Then came here, saw this issue and setup deploying apps on the homey. 
Status now:
Added the E14 bulb to the app, uploaded to my homey.
Readded the E14 bulb, now have on/off and dim functionallity. No light temperature as mentioned above.

Logging:
2017-09-17 21:07:52 [log] [OsramApp] init OsramApp
2017-09-17 21:10:08 [log] [ManagerDrivers] [lightify_e14] [0] ZigBeeDevice has been inited
2017-09-17 21:10:24 [log] [ManagerDrivers] [lightify_e14] [0] set onoff -> true
2017-09-17 21:10:26 [log] [ManagerDrivers] [lightify_e14] [0] set onoff -> false
2017-09-17 21:10:29 [log] [ManagerDrivers] [lightify_e14] [0] set onoff -> true
2017-09-17 21:11:50 [log] [ManagerDrivers] [lightify_e14] [0] set dim -> 0.29
2017-09-17 21:11:51 [log] [ManagerDrivers] [lightify_e14] [0] set dim -> 0.29
2017-09-17 21:12:17 [log] [ManagerDrivers] [lightify_e14] [0] set dim -> 0.44
2017-09-17 21:13:28 [log] [ManagerDrivers] [lightify_e14] [0] set onoff -> false
2017-09-17 21:13:29 [log] [ManagerDrivers] [lightify_e14] [0] set onoff -> true
2017-09-17 21:14:13 [log] [ManagerDrivers] [lightify_e14] [0] set onoff -> false

After this, trying some things, saw this error. Don't know if related.
2017-09-17 21:14:20 [err] [ManagerDrivers] [lightify_e14] [0] Error: could not perform off on genOnOff { Error: AF data
request fails, status code: 233. MAC no ack.
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1040)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:938)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1
:1401)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  message: 'AF data request fails, status code: 233. MAC no ack.' }

Would like to help getting the temperature working, let me know what to debug for this.

(have multiple e14 bulbs, the rest is still connected to the hue hub)

**Comment by Benjong** [comment]
@RobinBol Took me some time, but I found the bug why the E14 light doesn't do light_temperature.
The homey OS is case sensitive. 
In this line:
https://github.com/athombv/com.osram.lightify.zigbee/blob/411c38c164d91aa0c12e2a22925e4ce04d0505c3/node_modules/homey-meshdriver/lib/zigbee/system/capabilities/light_temperature/lightingColorCtrl.js#L3
it says Zig**b**eeDevice instead of Zig**B**eeDevice for the filename.

I only have e14 bulbs (and plugs), but i guess for none of the bulbs the light_temperature works.

So, the only thing needed for E14 is adding the driver and updating the app.json as stated above.

**Comment by RobinBol** [comment]
Ah the app uses an old version of the meshdriver dependency, the typo was fixed in the mean time, thanks for finding it. The app will be updated soon!

**Comment by RobinBol** [comment]
Updated the beta version of this app to support e14 and gu10 devices, if gardenspots should be added please give me information on the capabilities of the device and its ids.
