### ISSUE TITLE
Information Pairing/Reset Bulb

### ISSUE THREAD

**Issue by CyberSponk** [athombv/com.osram.lightify.zigbee#6]
The Information for Reset a Bulb is not correct. For Bulb A60, GU10, E14 and Garden-Spot: 5 Times > On for 5 Seconds, Off for 5 Seconds. After last Off turn on after 2 Seconds and wait till the bulb flashes once.

https://www.lightify.org/faq-de:
Lampen, Gardenspots, Downlights und das Flex zurücksetzen:
Um Lampen (Classic A, CLB 40, PAR16) oder Leuchten (Gardenspot, Flex, Downlight) in den Auslieferungszustand zurückzusetzen, schalten Sie sie fünfmal hintereinander für 5 Sekunden EIN und 5 Sekunden AUS. Nach erneutem Einschalten blinkt die Lampe einmal kurz zur Bestätigung und sie kann jetzt wieder in das System eingebunden werden.

https://www.lightify.org/faq
To reset lamps (Classic A, CLB 40, PAR16) and luminaires (Gardenspot, Flex, Downlight) back to their default settings, switch these ON for five seconds and OFF for five seconds, five times in succession. After switching on again, the lamp flashes shortly once to confirm – and can now be integrated into a LIGHTIFY system again.

**Comment by CyberSponk** [comment]
Hi, will check it again what Homey is shown and will come back.

**Comment by RobinBol** [comment]
The text I just posted is what Homey is currently showing as instructions.

**Comment by CyberSponk** [comment]
I mean that the part with 5 Seconds is not shown and ends on the part before "(". But will check.

**Comment by CyberSponk** [comment]
Looked at it: You're right. The Information is given full. Didn't know what i've seen. Think that the Number "6" irritiated me. Made reset more than once but didn't counted the last "On" where the Bulb should flashing if reset is correctly done. I'm Sorry.
